<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-09T04:08:59 IST" name="Default suite" finished-at="2021-09-09T04:08:59 IST" duration-ms="49">
    <groups>
    </groups>
    <test started-at="2021-09-09T04:08:59 IST" name="Default test" finished-at="2021-09-09T04:08:59 IST" duration-ms="49">
      <class name="base.code.testing">
        <test-method signature="noinput()[pri:0, instance:base.code.testing@61386958]" started-at="2021-09-09T04:08:59 IST" name="noinput" finished-at="2021-09-09T04:08:59 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noinput -->
        <test-method signature="singleinput()[pri:0, instance:base.code.testing@61386958]" started-at="2021-09-09T04:08:59 IST" name="singleinput" finished-at="2021-09-09T04:08:59 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[no negative numbers allowed-2 -4 ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: no negative numbers allowed-2 -4 
at base.code.Stringcalculator.Add(Stringcalculator.java:34)
at base.code.testing.singleinput(testing.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleinput -->
      </class> <!-- base.code.testing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
